// tasks.ts

// List of 50 random tasks
const tasks: string[] = [
    "Punch someone",
    "Hug a stranger",
    "Sing a song loudly",
    "Do 10 pushups",
    "Imitate a celebrity",
    "Dance for 30 seconds",
    "Run around in circles",
    "Pretend you're an airplane",
    "Act like a chicken for 1 minute",
    "Do your best evil laugh",
    "Talk like a pirate for the next 5 minutes",
    "Do a handstand (or try)",
    "Eat a spoonful of mustard",
    "Pretend you're in a soap opera",
    "Pretend you’re a cat",
    "Prank call a friend",
    "Speak only in questions for 2 minutes",
    "Give a motivational speech",
    "Do a silly walk across the room",
    "Speak in a fake accent for the next 3 minutes",
    "Do the worm dance move",
    "Pretend to be a robot",
    "Recite a poem dramatically",
    "Do your best animal impression",
    "Do 20 jumping jacks",
    "Act like a superhero for 2 minutes",
    "Walk like a crab for 1 minute",
    "Pretend to be a waiter and take everyone’s fake order",
    "Do the Macarena dance",
    "Pretend to swim on the floor",
    "Whisper everything for the next 5 minutes",
    "Balance a spoon on your nose",
    "Pretend you’re a statue for 1 minute",
    "Do a TikTok dance",
    "Pretend you're giving a weather report",
    "Spin around 10 times and then walk in a straight line",
    "Pretend to be in slow motion",
    "Act like you're stuck in a box",
    "Say the alphabet backwards",
    "Make up a rap about the people in the room",
    "Pretend you're a baby",
    "Try to lick your elbow",
    "Mime riding a horse for 1 minute",
    "Do the moonwalk",
    "Pretend you're a famous chef explaining a recipe",
    "Speak gibberish for the next 2 minutes",
    "Pretend to be an opera singer",
    "Make an animal sound after every sentence for the next 5 minutes",
    "Pretend you’re playing a guitar solo",
  ];
  
  // List of 150 funny options
  const options: string[] = [
    "on the head",
    "person next to you",
    "in the bathroom",
    "while balancing on one foot",
    "in slow motion",
    "blindfolded",
    "while holding your nose",
    "while spinning around",
    "in a British accent",
    "like you’re underwater",
    "in the mirror",
    "while hopping like a frog",
    "with your eyes closed",
    "like you’re a ninja",
    "on top of the couch",
    "while lying on the floor",
    "as if you’re 100 years old",
    "like you’re in a horror movie",
    "like a robot",
    "while holding your breath",
    "like a magician",
    "with jazz hands",
    "with your hands behind your back",
    "while doing the splits (or attempting to)",
    "like a cartoon character",
    "in slow-motion",
    "like you’re teaching a kindergarten class",
    "like a rock star",
    "in the style of a TV commercial",
    "like a news reporter",
    "while flapping your arms like a bird",
    "like you’re in an action movie",
    "while balancing something on your head",
    "while dancing the cha-cha",
    "like you’re in a musical",
    "as if you’re a rapper",
    "while pretending to juggle",
    "like you’re narrating a nature documentary",
    "while standing on one leg",
    "as if you’re a superhero",
    "while pretending to be a famous singer",
    "like you're a comedian",
    "while spinning a fidget spinner",
    "in slow-motion like you're in The Matrix",
    "while pretending to surf",
    "like you’re conducting an orchestra",
    "while balancing a pillow on your head",
    "as if you’re being chased by a ghost",
    "like you’re underwater",
    "as if you’re stuck in quicksand",
    "with your hands over your ears",
    "like you’re on a trampoline",
    "while pretending to fly a plane",
    "while playing air guitar",
    "like you’re in outer space",
    "like you’re a secret agent",
    "while doing the chicken dance",
    "like you’re underwater",
    "while pretending to eat spaghetti",
    "as if you’re in a wrestling match",
    "like you’re in a kung fu movie",
    "while moonwalking",
    "while acting like a mime",
    "while juggling imaginary balls",
    "like you’re in a rap battle",
    "while pretending to be a cowboy",
    "while holding a plank position",
    "like you’re playing a video game",
    "as if you’re in a spy movie",
    "while pretending to shoot a basketball",
    "while pretending to be a DJ",
    "like you’re on a rollercoaster",
    "as if you’re walking a tightrope",
    "like you're in a soap opera",
    "while whispering everything",
    "as if you’re an astronaut",
    "while pretending to hula hoop",
    "like you’re a statue",
    "as if you’re ice skating",
    "while pretending to drive a racecar",
    "while pretending to ride a bike",
    "like you’re a fashion model",
    "while acting like a zombie",
    "while miming a balloon animal",
    "as if you’re being chased by bees",
    "while acting like a famous detective",
    "like you’re an alien",
    "like you’re in a medieval movie",
    "as if you’re playing an invisible violin",
    "while acting like a ninja turtle",
    "like you’re talking to your pet",
    "while pretending to box",
    "like you're the king of a castle",
    "like you’re directing a movie",
    "as if you’re a stand-up comedian",
    "while pretending to fly a helicopter",
    "while pretending to blow bubbles",
    "like you’re a magician performing a trick",
    "like you’re walking through a swamp",
    "while riding an imaginary horse",
    "as if you’re trying to catch a fish",
    "while pretending to play a flute",
    "as if you’re telling a spooky story",
    "while pretending to be a lion tamer",
    "like you’re a lifeguard",
    "as if you’re training for the Olympics",
    "while trying to balance a book on your head",
    "as if you’re a penguin",
    "while pretending to chop vegetables",
    "like you’re starring in a commercial",
    "while acting like you’re underwater",
    "as if you’re trying to win a marathon",
    "like you’re narrating a cooking show",
    "as if you’re being chased by an invisible monster",
    "while pretending to be a dancer",
    "as if you’re climbing a mountain",
    "like you’re leading a marching band",
    "while pretending to play a trumpet",
    "like you’re in an animated movie",
    "while pretending to be a photographer",
    "as if you’re a famous actor",
    "like you’re being interviewed on TV",
    "while pretending to be a race car driver",
    "as if you’re training for a dance competition",
    "like you’re a sports commentator",
    "while miming being trapped in a box",
    "while pretending to make pizza",
    "like you're a wrestler getting ready for a match",
    "as if you’re writing a love letter",
    "while pretending to be a bird",
    "like you’re on a treasure hunt",
    "while pretending to paint a masterpiece",
    "as if you’re directing a photoshoot",
    "like you're a referee in a sports game",
    "while pretending to be a famous explorer",
    "as if you’re a ninja on a mission",
  ];
  
  // Export the tasks and options arrays
  export { tasks, options };
  